version: "3.1"

services:
  tileserver-gl:
    image: fa7ad/tileserver-gl-slim:latest
    volumes:
      - "./:/data"
    ports:
      - 80
    expose:
      - 80

  nginx:
    image: nginx:stable
    ports:
      - "80:80"
    volumes:
      - "nginx-cache:/cache-data"
      - "./nginx.conf:/etc/nginx/nginx.conf"

volumes:
  nginx-cache:
